version: '3.8'

services:
   minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "4G"
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./minecraft/data:/data
