---
# services:
#   satisfactory:
#     build:
#       context: ./satisfactory
#     restart: unless-stopped
    # deploy:
    #       resources:
    #         reservations:
    #           memory: 12G
#     container_name: satisfactory-server
#     ports:
#       - 7777:7777/udp
#       - 7777:7777/tcp
#     volumes:
#       - ./satisfactory/data:/home/steam/Satisfactory-dedicated

services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - 7777:7777/udp
            - 7777:7777/tcp
        volumes:
            - './satisfactory/config:/config'
        environment:
            MAXPLAYERS: 4
            PGID: 1000
            PUID: 1000
            ROOTLESS: false
            STEAMBETA: false
        restart: unless-stopped
        deploy:
          resources:
            reservations:
              memory: 12G