version: '3.8'

services:
  satisfactory:
    build:
      context: ./satisfactory
    restart: always
    container_name: satisfactory-server
    labels:
      - "traefik.enable=false"
    ports:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp
    volumes:
      - ./satisfactory/data:/home/steam/Satisfactory-dedicated
