services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
            - '8888:8888/tcp'
        volumes:
            - './satisfactory/config:/config'
        environment:
            MAXPLAYERS: 4
            PGID: 1000
            PUID: 1000
            ROOTLESS: false
            STEAMBETA: false
        restart: unless-stopped
        deploy:
          resources:
            reservations:
              memory: 12G
